# Generated by Django 3.2.9 on 2021-12-06 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='sub_total',
            field=models.IntegerField(default=0),
        ),
    ]
